CREATE TABLE IF NOT EXISTS raw.disaster_declarations (
    id UUID PRIMARY KEY,
    fema_declaration_string VARCHAR(20),
    disaster_number INTEGER,
    state VARCHAR(2),
    declaration_type VARCHAR(5),
    declaration_date TIMESTAMP,
    fy_declared INTEGER,
    incident_type VARCHAR(50),
    declaration_title TEXT,
    ih_program_declared BOOLEAN,
    ia_program_declared BOOLEAN,
    pa_program_declared BOOLEAN,
    hm_program_declared BOOLEAN,
    incident_begin_date TIMESTAMP,
    incident_end_date TIMESTAMP,
    disaster_closeout_date TIMESTAMP,
    tribal_request BOOLEAN,
    fips_state_code VARCHAR(2),
    fips_county_code VARCHAR(3),
    place_code VARCHAR(10),
    designated_area VARCHAR(100),
    declaration_request_number VARCHAR(10),
    last_ia_filing_date TIMESTAMP,
    incident_id VARCHAR(20),
    region INTEGER,
    designated_incident_types VARCHAR(50),
    last_refresh TIMESTAMP,
    hash VARCHAR(40),
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);